### PR TITLE
add async EventEmitter

### PR DESCRIPTION
**Pull request by gobeli**
This is a pull request to enable async tasks in event handlers. (#1359)

Don't know if this was planned at all, but I thought it would be a cool feature.

The additional file changes were made automatically by the linter.

### CODE REVIEW

**Comment by binyamin** [comment]
Thanks for the PR!
@zachleat Looks fine to me.

**Comment by dafiulh** [comment]
this should be shipped in v11.1 😕

**Comment by zachleat** [comment]
@dafiulh did you post this comment after 0.11.1 had already shipped?

**Comment by dafiulh** [comment]
@zachleat yes, I just realized I needed this after trying to use v0.11.1 `afterBuild` event

**Comment by zachleat** [comment]
Merged, this will go up with 1.0—thank you!

**Comment by zachleat** [comment]
Just fair warning I did a slight refactor to use the `listeners` method instead of the private `this._events` reference.

**Pull request merged**
