### PR TITLE
refactor: Prefer `const` where appropriate

### PR DESCRIPTION
**Pull request by Zearin**
I just used eslint’s `--fix` option for a single rule, `prefer-const`.

**Rationale:**
From the [`prefer-const`](https://eslint.org/docs/latest/rules/prefer-const) page:

> If a variable is never reassigned, using the `const` declaration is better.
>
> `const` declaration tells readers, “this variable is never reassigned,” reducing cognitive load and improving maintainability.

### CODE REVIEW

**Comment by Zearin** [comment]
(Also, I dunno if the engine does any sort of optimization for `const` variables, but it’s possible…I guess? 🤷 )

**Comment by uncenter** [comment]
Side note: Eleventy doesn't use conventional commits so this doesn't really matter, but this PR technically would be a `refactor:`, not a `chore:`.

**Comment by Zearin** [comment]
@uncenter Thanks! I have been trying to use conventional commits on my own just in case they could come in handy, but never used them on a team or anything. I appreciate the lesson! 🙏🏽 

Edited the title of the PR. (I don't _think_ I can reword the commit without force-pushing, though…)

**Comment by Zearin** [comment]
@zachleat Rebased! Can you take a look when you have the chance?

**Review by Zearin — COMMENTED** [review]
@zachleat I know you were OOO for a while. When you’re back, can you take a look when you have a moment?

**Comment by Zearin** [comment]
I’ll try this again later. :P

**Comment by zachleat** [comment]
Apologies—please check in before starting a large change like this! I would have cautioned—as the code suggests I prefer `let`.

**Pull request closed without merging**
