### PR TITLE
update .gitignore

### PR DESCRIPTION
**Pull request by inetbiz**
Spelling Typo; cPanel specific folders generated

### CODE REVIEW

**Comment by zachleat** [comment]
I don’t think I’m aware of why this is needed—in what situations are cPanel directories generated?

**Comment by inetbiz** [comment]
> I don’t think I’m aware of why this is needed—in what situations are cPanel directories generated?

https://www.phusionpassenger.com/library/walkthroughs/deploy/nodejs/ownserver/apache/oss/el7/deploy_app.html#login-to-your-server-create-a-user-for-the-app cPanel NodeJS requires mod_phusion. It generates default folders. That being public and tmp. `public` being the output folder. It inserts .htaccess file to control cPanel stuff.. cPanel then inserts .well-known/pki-validation/

**Comment by zachleat** [comment]
Sorry, I’m still not following. What’s the workflow here? I’m assuming this isn’t doing a standard `node_modules` installation. Are you checking out this repo into a cPanel controlled diretory?

**Comment by inetbiz** [comment]
Me or anyone else using cPanel with Cloudlinux. I'll have to check around if the environment is different w/o Cloudlinux. https://docs.cpanel.net/knowledge-base/web-services/how-to-install-a-node.js-application/

**Comment by zachleat** [comment]
Oh, oh—just to be super clear, changes to this repository’s `.gitignore` folder won’t apply downstream to any projects using Eleventy. This file only affects the source code for Eleventy specifically, not Eleventy projects.

Sorry to belabor this but with that in mind—does this still seem relevant?

**Comment by inetbiz** [comment]
Up to you? Millions of cpanel hosted domains.

**Comment by pdehaan** [comment]
@inetbiz But are you installing eleventy via <kbd>npm install @11ty/eleventy</kbd> or are you using <kbd>git clone ...</kbd>?

**Comment by zachleat** [comment]
Closing this one, sorry. I don’t quite understand the benefit yet!

**Pull request closed without merging**
