### PR TITLE
Showcase silent crash: this demos the type of crash fixed with pullreq #1079

### PR DESCRIPTION
**Pull request by GerHobbelt**
This crux is the rethrow (`throw ex;`) in there: such a deliberate exception (or any other failure in this code) should cause the app-level registered exception handler to kick in but no such luck.

The fix is #1079

# WARNING:

do NOT merge this pullreq. It's only there to showcase the issue.

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
> do NOT merge this pullreq. It's only there to showcase the issue.

Hm, GitLab has the feature, that if you prepend a `WIP: ` to the PR title, it will be flagged as non-mergeable. Not sure, whether GitHub behaves the same way by now …

**Comment by stevenpetryk** [comment]
@Ryuno-Ki you can open a ["draft PR"](https://github.blog/2019-02-14-introducing-draft-pull-requests/) that can't be merged unless the author marks it as "ready for review".

**Comment by Ryuno-Ki** [comment]
Ah, nice one! Must have missed the news announcing this, so thanks for bringing it to my attention.

**Comment by zachleat** [comment]
Confirmed this is fixed and errors appropriately 
image

**Pull request closed without merging**
