### PR TITLE
Makes stopWatch() async and graceful.

### PR DESCRIPTION
**Pull request by VividVisions**
This is the counterpart to https://github.com/11ty/eleventy-dev-server/pull/85.

### CODE REVIEW

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.17 Thank you!!

**Comment by zachleat** [comment]
FYI I did need to revert the `process.exit()` removal here. ⌘+C wasn’t stopping the process.

**Comment by zachleat** [comment]
This isn’t a currently tested scenario, unfortunately. Can you check the changed I made linked above and see if they still align?

**Comment by VividVisions** [comment]
I'm sorry, my description of this PR should have been more thorough.

This PR goes hand in hand with my PR in eleventy-dev-server (https://github.com/11ty/eleventy-dev-server/pull/85). They need each other to work properly. Applying only one but not the other doesn't improve anything, unfortunately.

Regarding the process not stopping, my best guess is: The current dev-server doesn't close the WebSocket connection(s), which would prevent a clean exit. Reintroducing `process.exit()` actually renders both PRs moot since it prevents a graceful shutdown. :(

Please let me know if I can support you in any way.

**Comment by zachleat** [comment]
Restored your original changes and they’ll ship with Dev Server v2.0.2 in 3.0.0-alpha.18—thank you so much!

**Comment by VividVisions** [comment]
That's awesome! Thank you!

**Pull request merged**
