### PR TITLE
chore: upgrade 2x performant LiquidJS v9

### PR DESCRIPTION
**Pull request by harttle**
There're substantial performance improvements in v9 and many bugfixes from v6 to v9. There're some API changes and some of them can be indicated in this PR:

* inside custom tag implementation, `engine.renderer.renderTemplates()` can be used only in generator tags as you can see in `addPairedShortcode()`. The difference is subtle here but generator tags provides [a major performance boost](https://github.com/harttle/liquidjs/pull/166) and provide code reuse between sync/async.
* `evalValue` is now changed to async and another `evalValueSync()` is added for sync calls.
* some methods (see the following`evalValue()` `in parseArguments()`) are nolonger static.

A good thing I find is that for people using Liquid via `setEngineLib()` will not be affected. 

Another thing is, the patch is automatically formatted by your git hooks, is it supposed to be this way or should I disable those hooks and re-submit? Thank you for you time!

### CODE REVIEW

**Comment by zachleat** [comment]
Beautiful, thank you!

Are you saying this isn’t a breaking change for any of the template language syntax?

**Comment by zachleat** [comment]
Fixes #469

**Comment by harttle** [comment]
> Are you saying this isn’t a breaking change for any of the template language syntax?

There should be no breaking changes except for some undocumented features (I mean some fault tolerance provided by LiquidJS but not by Shopify/liquid or Jekyll like [#212](https://github.com/harttle/liquidjs/issues/212)). Additionally, the filters should be more robust after all these bug fixes.

**Comment by aciccarello** [comment]
Updating Liquid would also update strftime used by the date filter. I was confused why the strftime docs didn't match what I was seeing.
harttle/liquidjs#77

**Comment by harttle** [comment]
@aciccarello Thank you to point it out. I've updated the doc for [more specific description of strftime](https://github.com/harttle/liquidjs/commit/2fa4edaa84ea1cd76c27a171f0719105f94878f9). Basically it should be conformant to Ruby's core [DateTime#strftime](https://apidock.com/ruby/DateTime/strftime). If there's still anything unexpected, feel free to open an issue on [harttle/liquidjs](https://github.com/harttle/liquidjs/issues).

**Comment by zachleat** [comment]
Shipping this! Thank you!

**Pull request merged**
