### PR TITLE
bump chokidar to v4

### PR DESCRIPTION
**Pull request by talentlessguy**
Removes 11 dependencies, includes better types

Passes all tests

Draft for now because needs bumping in dev-server as well

### CODE REVIEW

**Comment by zachleat** [comment]
Sorry—we can’t do this yet per notes made at #3442. Clearly we need some additional test coverage there

**Comment by talentlessguy** [comment]
is it okay if I add tests with a glob matcher (using `fast-glob` which is already a dependency) or it's still a no?

**Comment by zachleat** [comment]
oh, yeah for sure! The plan is to upgrade to v4, internally we rely on that globs feature so we’d need to make sure that doesn’t break when we upgrade. Some more notes on that here: https://www.11ty.dev/docs/watch-serve/#add-your-own-watch-targets

**Comment by talentlessguy** [comment]
how would a test for it look like? should I use fixtures for it?

**Pull request closed without merging**
