### PR TITLE
docs: document capitalize utility

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
This function is mainly used as filter. It assumes standard Unicode
case mappings. That is, it can have surprising for certain locales
such as Turkey:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase

I was wondering, whether a lesson could be learned by Lodash,
which defines several helper functions to transform into different
casings. This function here could then defer to the respective
transformation.

Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

### CODE REVIEW

**Comment by zachleat** [comment]
I don’t think that utility is even being used in a way that makes sense. Might make more sense to refactor it out

**Comment by Ryuno-Ki** [comment]
I can see it's used, but without the option. Thus, it can be simplified. Shall I refactor?

**Comment by zachleat** [comment]
Ah sorry I just went ahead and got rid of it—thanks for the prompt!

**Comment by Ryuno-Ki** [comment]
No worries. I'm going on the hunt for another function then :-)

**Pull request closed without merging**
