### PR TITLE
Add Twig support

### PR DESCRIPTION
**Pull request by pieterbeulque**
### Background

I want to use Eleventy as much as possible, but often have to migrate work later to either Craft or WordPress (using Timber), which means having to convert everything to Twig.

Nunjucks was an option but didn't cover everything, so here we are 😁 

### Status

I copied over all Nunjucks-related code and am now trying to make all tests pass as a start. I guess we'll go from there and keep this PR open for status updates.

Feel free to collaborate.

### Related

See #143

### CODE REVIEW

**Comment by pieterbeulque** [comment]
@zachleat - How important is it to match templating functionality across all templating languages?

I found this table as an overview of possible Twig extensions and think it'd be best to stick to what the language supports, instead of doing tricks like [`10da170`](https://github.com/11ty/eleventy/pull/656/commits/10da170d350d0ff27f7d51337474b1ac6e51a667).

```========== ========================== ========== =========================
What?      Implementation difficulty? How often? When?
========== ========================== ========== =========================
*macro*    trivial                    frequent   Content generation
*global*   trivial                    frequent   Helper object
*function* trivial                    frequent   Content generation
*filter*   trivial                    frequent   Value transformation
*tag*      complex                    rare       DSL language construct
*test*     trivial                    rare       Boolean decision
*operator* trivial                    rare       Values transformation
========== ========================== ========== =========================
```

**Comment by pieterbeulque** [comment]
🎉 I just went through the whole _Getting started_ section of the Eleventy-documentation with Twig templates and everything works! 🎉

**Comment by pieterbeulque** [comment]
This is ready (with minimum functionality), but I can't get relative includes to work because of how Twig works with the filesystem. Any pointers on how this was fixed for e.g. Nunjucks (if that works the same) would be very welcome.

**Comment by tylersticka** [comment]
This progress is exciting! It would make transitioning from or sharing resources with [Timber](https://www.upstatement.com/timber/) _way_ easier.

> This is ready (with minimum functionality), but I can't get relative includes to work because of how Twig works with the filesystem.

I'm a bit stumped as well, as you're already using [`TwingLoaderChain`](https://ericmorand.github.io/twing/api.html#twingloaderchain) with both a relative and absolute loader (which is what I would have tried). 🤔

**Comment by pieterbeulque** [comment]
> It would make transitioning from or sharing resources with Timber way easier.

That's my use case as well! My CMS-backed work is either in Craft CMS (Twig) or WordPress (Twig through Timber).

> you're already using TwingLoaderChain with both a relative and absolute loader (which is what I would have tried).

Yeah, I thought that'd be a fix, but how I understand it, Eleventy grabs a file's contents and parses it (to handle frontmatter etc) and passes that contents as a string to the templating engine. So you're in fact always falling back to the StringLoader, that has no notion of where the sourcefile lived on the filesystem. That's where I'm stuck now.

I got to a point where I got it working from the filesystem, and includes worked, but then it didn't support any of the other Eleventy features like frontmatter etc.

**Comment by pieterbeulque** [comment]
🎉 I managed to move an [existing Eleventy-based website](https://mementowoordfestival.be) that was using Nunjucks to Twig successfully!

Two things threw errors compared to Nunjucks:

1. `foo|safe` had to change to `foo|raw`
2. `foo|replace('foo', bar')` has to change to `foo|replace({ 'foo': 'bar' })`

But I guess that means this works as a basic implementation and might be worth merging upstream, regardless of the known issues with relative imports and other (more advanced) Eleventy features?

**Comment by zomars** [comment]
Is something preventing this PR to be merged?  I would love to finally use twig with 11ty! 🙌

**Comment by pieterbeulque** [comment]
Hi @zomars, it will probably have lots of oddities and bugs, but as a first version I think it's ready to be used in the wild.

**Comment by zachleat** [comment]
I really love this work! However my hunch is that this should go after #117 as a plugin. Really trying to avoid more languages in core right now, unless they’re super popular, so I don’t get too overloaded here. Happy to leave this open and continue the discussion though

**Comment by pieterbeulque** [comment]
@zachleat Totally get that, I agree that core shouldn't try to support everything 🙂I'm cool with moving this into some kind of plugin

**Comment by zomars** [comment]
Or maybe we could add this last one? 😅

**Comment by zachleat** [comment]
Going to close this for now—sorry! Please follow along at #117!

**Comment by cbirdsong** [comment]
Has this been moved to a plugin anywhere?

**Comment by zachleat** [comment]
It lives! https://www.npmjs.com/package/@factorial/eleventy-plugin-twig Also note that #143 is the home base for this one

**Comment by pieterbeulque** [comment]
Let's go! Thanks to everyone involved! 🚀

**Pull request closed without merging**
