### PR TITLE
docs(README): list currently known eleventy plugins on npm in README. refs #405

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

### CODE REVIEW

**Comment by zachleat** [comment]
Hey @Ryuno-Ki I don’t actually want these to live on the GitHub readme, sorry about that! I would much rather they live on https://www.11ty.io/docs/plugins/ via https://github.com/11ty/11ty.io/blob/master/docs/plugins.md

**Comment by DirtyF** [comment]
We could teach people how to fish with `npm search eleventy-plugin` 🔎

**Comment by zachleat** [comment]
Yes!

For the record I’m fine with a link from the README.md to the plugins documentation! I just want to keep the `11ty/eleventy` README.md very simple for now to funnel people to the official docs if possible.

**Comment by Ryuno-Ki** [comment]
Opened https://github.com/11ty/11ty.io/pull/146 instead.

**Comment by Ryuno-Ki** [comment]
See also https://github.com/11ty/eleventy/pull/570

**Pull request closed without merging**
