### PR TITLE
Make glob matching case insensitive

### LINKED ISSUE #509: Case insensitive file formats
Currently the default set of file formats is all lower case.  On windows, some tools I've used generated file names with uppercase extensions.  Running eleventy just ignored these files and it took a bit of troubleshooting to determine what the issue is.

I have a feeling that just enabling case insensitivity might be a pretty big can of worms, but what about enabling it by default only on Windows and allowing an override in config?

### PR DESCRIPTION
**Pull request by veleek**
Fixes #509 

Note: I also added the `onlyFiles` flag since I BELIEVE we probably only want files, but someone can correct me if I'm wrong.

### CODE REVIEW

**Comment by zachleat** [comment]
Hey @veleek can you add a test for this too? Probably pretty easy to work from this one: https://github.com/11ty/eleventy/blob/master/test/EleventyFilesTest.js#L9

**Comment by zachleat** [comment]
(I think `onlyFiles` is fine here yeah) Related docs: https://github.com/mrmlnc/fast-glob#onlyfiles

**Comment by veleek** [comment]
@zachleat  - Test added!

**Comment by veleek** [comment]
Re-opening to trigger CI build again.  Appears to have failed for an unrelated reason.

**Comment by veleek** [comment]
And a DIFFERENT random test failed this time.

**Comment by kleinfreund** [comment]
Looks like the tests pass this time around.

**Comment by zachleat** [comment]
Just unrelated to this review, were the tests failing from the Windows versions of Travis?

**Comment by zachleat** [comment]
LGTM thanks!

**Comment by veleek** [comment]
@zachleat - Yes, I believe it was the Windows tests failing only.

**Pull request merged**
