### PR TITLE
Support for cjs extension in global and local data files

### PR DESCRIPTION
**Pull request by gloryofrobots**
Implements support of `.cjs` (common js) extension in global and local data files as requested in #837  Places `.cjs` before `.js` in priority ordering for local files. For global data order, I need to wait while #821 gets merged.
Changes are very trivial in both the TemplateData.js and tests but a lot of tests were changed due to local data file lists checks.

### CODE REVIEW

**Comment by zachleat** [comment]
Now that #821 is merged do we need to make additional changes here?

**Comment by gloryofrobots** [comment]
I need to add some changes to this PR based on #821 approval and resolve conflicts. I probably will commit a new version on weekend

**Comment by gloryofrobots** [comment]
There is a bug in a new version of the ava test runner.  It injects some custom stuff into require.extensions and brakes `require()`  so it can not load `cjs` files. I will try to make a fix for ava but for now, I can't push my code

**Comment by zachleat** [comment]
Oh well that’s terrible @gloryofrobots!

Some discussion about this here https://github.com/avajs/ava/issues/2293

**Comment by gloryofrobots** [comment]
I made a [PR](https://github.com/avajs/require-precompiled/pull/2) for ava (or to be precise for a small project in the ava domain) which is hopefully will fix the problem. But I do not know when it will be merged. The good news is that because it is not a fix for Ava itself but for Ava dependency the adoption may be faster.

**Comment by gloryofrobots** [comment]
Ava team merged my fix! I will update this branch soon

**Comment by gloryofrobots** [comment]
Ok, work is done. I bumped ava/babel version in package.json to 1.0.1 to include fix for the bug mentioned above.

**Comment by gloryofrobots** [comment]
Fixed new conflicts

**Comment by zachleat** [comment]
YESSSSS Thank you for your awesome work here, including going above and beyond and fixing a dependency too! Wow!

**Pull request merged**
