### PR TITLE
Feat: 1254 Allow customize tags behaviour

### PR DESCRIPTION
**Pull request by sielay**
[x] rename tags collection using `config.keys.tags`
[x] prevent tags polluting collections object
[x] move tags to entry nested in collections object

### CODE REVIEW

**Comment by sielay** [comment]
@zachleat Any chances of merging this in?

**Comment by zachleat** [comment]
Discussion at #1254

**Comment by boehs** [comment]
I think this pr should be revisited. Perhaps a configuration property `collectionsFromFrontmatterProperties` (name is up for discussion :P) with a default value of `["tags"]` to make `collections.tags` work. I could add a second item like catagories to that array and get `collections.catagories`

**Comment by sielay** [comment]
@zachleat I'd be updating my sites using this branch. Have you made any similar changes since or provided a simpler, native way to work with multiple taxonomies? Thanks

**Comment by sielay** [comment]
I updated the branch. Will test it in the following days.

**Comment by sielay** [comment]
Closing as it requires redoing

**Pull request closed without merging**
