### PR TITLE
Check if the .gitignore is empty and if it is ignore node_modules.

### PR DESCRIPTION
**Pull request by danielstaleiny**
This pull request refer to #389

### CODE REVIEW

**Comment by zachleat** [comment]
I like where you’re going here. I would prefer if we could get the file contents and trim to length so we could make this work if the file just has whitespace, too?

Also can you change this so it doesn’t modify any of the existing tests? Not sure why the folders needed to be changed there

**Comment by danielstaleiny** [comment]
Main reason for re-ordering the test was that I wanted them to be logically grouped.

**Comment by danielstaleiny** [comment]
I squashed the changes.  all the changes are in the last commit.

**Comment by zachleat** [comment]
Ah ah, I see. Yeah I can see the temptation for that. Modifying existing tests is a big red flag when I’m reviewing things—if you’d like to reorder them I’m happy to accept a new PR that does only this (thank you and sorry 😱)

**Pull request merged**
