### PR TITLE
Replace Chalk with Kleur

### PR DESCRIPTION
**Pull request by dgrammatiko**
# A simple switch of a cli dependency

### Why?
- Kleur is smaller (theoretically better(?) for the serverless)
Screenshot 2021-11-20 at 22 41 46

- Kleur is more performant
Screenshot 2021-11-20 at 23 23 12

- it has no further dependencies

- Micro optimisation? Maybe, maybe not...

### CODE REVIEW

**Comment by zachleat** [comment]
Seems great to me, thanks!

**Comment by TigersWay** [comment]
There's quite some choice to replace chalk. But is that the best one really? I found quite different numbers around... Do you want small or fast?

**Comment by dgrammatiko** [comment]
@TigersWay small size and no dependencies were my goals here but I guess the rabbit hole is deeper. So, some further research on styling the cli revealed these options:

- [Chalk](https://github.com/chalk/chalk) has 2 dependencies, it's the most popular pkg
Screenshot 2021-11-21 at 13 29 03

- [kleur](github.com/lukeed/kleur) has 0 dependencies, it's also popular and has better performance
Screenshot 2021-11-21 at 13 30 45

- But [colorette](github.com/jorgebucaran/colorette) has also 0 dependencies, it's smaller and more performant (according their benchmarks)
Screenshot 2021-11-21 at 13 31 59


- But then [picocolors](github.com/alexeyraspopov/picocolors) has also 0 dependencies, it's even smaller more performant and used by PostCSS and Autoprefixer
Screenshot 2021-11-21 at 13 34 41

@zachleat since all these are interchangeable packages let me know if you want me to create a new PR switching to picocolors (or any other package that you think it's a better fit)

**Comment by TigersWay** [comment]
@dgrammatiko  You have them all 😄 Thanks!

colorette and the recent picolors are clearly both small and much faster than chalk, which is A LOT more used.....
Another choice to make 😇

**Comment by pdehaan** [comment]
This is giving me https://github.com/babel/babel/pull/13783 (and https://github.com/eslint/eslint/pull/15102) flashbacks.

I think the best point in the Babel thread was Sindre's comment: https://github.com/babel/babel/pull/13783#issuecomment-927317201

> _Also, Chalk is such a common dependency that it's usually already somewhere in the dependency tree on most projects anyway. So Chalk is often 0 kB._

Also interesting is that if you do a brand new Eleventy 0.12.1 install, the node_modules directory is ~76MB (on macOS at least), so not sure we we're saving by reducing the package size by 5KB.

Looking at the dependency tree, it looks like @11ty/eleventy 0.12.x includes chalk 3 times, but all very different versions.

```sh
npm ls chalk

tmp@1.0.0 /private/tmp/11ty-size
└─┬ @11ty/eleventy@0.12.1
  ├─┬ browser-sync@2.27.7
  │ └─┬ eazy-logger@3.1.0
  │   └─┬ tfunk@4.0.0
  │     └── chalk@1.1.3
  ├── chalk@4.1.2
  └─┬ time-require@0.1.2
    └── chalk@0.4.0
```

And @11ty/eleventy 1.0.0-beta.8 includes chalk 4 times, each with a different major version number.

```sh
npm ls chalk

11ty-size@1.0.0 /private/tmp/11ty-size
└─┬ @11ty/eleventy@1.0.0-beta.8
  ├─┬ browser-sync@2.27.7
  │ └─┬ eazy-logger@3.1.0
  │   └─┬ tfunk@4.0.0
  │     └── chalk@1.1.3
  ├── chalk@4.1.2
  ├─┬ ejs@3.1.6
  │ └─┬ jake@10.8.2
  │   └── chalk@2.4.2
  └─┬ time-require@0.1.2
    └── chalk@0.4.0
```

**Comment by dgrammatiko** [comment]
> This is giving me babel/babel#13783 (and eslint/eslint#15102) flashbacks.

What have I done? 😒 I was genuinely unaware of these PRs...

> And @11ty/eleventy 1.0.0-beta.8 includes chalk 4 times, each with a different major version number.

Yes, but that's due to other dependencies, as you already showcasing by the dep tree graph. Also if chalk was a direct dependency (as it was before this PR) there would be 5 copies of the library.

**Comment by pdehaan** [comment]
No objections here. Looking at the dep trees above, it looks like chalk@4 wasn't already in the tree anyways. :+1:

**Pull request merged**
