### PR TITLE
Ensures origin path isn’t included in output when targeting a directory

### LINKED ISSUE #90: `addPassthroughCopy` target
So, all my templates and such live in `/_src` and everything gets written to `/_site`, just to keep the [repo root](https://github.com/Wilto/wilto-makes-food) tidy.

```javascript
dir: {
    input: "_src",
    includes: "_includes",
    data: "_data",
    output: "_site"
  }
```

The “and such” includes images, so: `eleventyConfig.addPassthroughCopy("_src/img");`—but they end up getting written to `/_site/_src/img`.

Assuming I’m not doing something wrong here, should `addPassthroughCopy` be set up to accept an (optional) target argument? Something like:

```javascript
eleventyConfig.addPassthroughCopy( "_src/img", "_site/_assets/img" );
```

If it sound feasible, I might be able to take a crack at it.

### PR DESCRIPTION
**Pull request by Wilto**
Fixes #90

### CODE REVIEW

**Comment by zachleat** [comment]
Huh, I think I set you up to fail here—ugh—sorry. That TemplatePassthrough object isn’t even getting the right information to create the correct output paths there. I’ve checked in some more code to master to assist you, if you pull that in here.

I think `getOutputPath()` will look something like this:

```
getOutputPath() {
  return TemplatePath.normalize(this.outputDir, TemplatePath.stripPathFromDir(this.path, this.inputDir));
}
```

**Comment by zachleat** [comment]
We just want to remove the input `src` dir from the output path and keep the rest of the directory structure intact.

**Comment by Wilto** [comment]
please hold while i un-donk-up my fork’s history

**Comment by zachleat** [comment]
Thanks!!

**Pull request merged**
